config/routes.rb
Rails.application.routes.draw do

 resources :restaurants do
  resources :reviews
 end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese","italian","japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: [1,2,3,4,5], allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render "new"
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render "edit"
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    @restaurant.reviews.create(reviews_params)
    redirect_to restaurant_path(@restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def reviews_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
      <script src="https://use.fontawesome.com/55889b2b86.js"></script>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">

      <%= simple_form_for(@restaurant) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category %>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
Editing Restaurant
<%= render 'form', restaurant: @restaurant %> <%= link_to 'Show', @restaurant %> | <%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= restaurant.category %></td>
        <td><%= link_to 'Show the restaurant', restaurant_path(restaurant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p></p>
<p><%= link_to "Create a new restaurant", new_restaurant_path(@restaurant) %></p>

app/views/restaurants/new.html.erb
New Restaurant
<%= render 'form', restaurant: @restaurant %> <%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p><%= link_to "Home", restaurants_path do %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @restaurant.phone_number %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>

<p><%= link_to edit_restaurant_path(@restaurant) do %><i class="fa fa-eye" aria-hidden="true"></i><% end %></p>

<p><%= link_to restaurant_path(@restaurant), method: :delete, data: {confirm: 'Are you sure?' } do %></p><i class="fa fa-trash" aria-hidden="true"></i><% end %>

<div class="container">
  <h3>Reviews:</h3>
  <ul>
  <% @restaurant.reviews.each do |review| %>
    <li class="review-card col-md-6 col-md-offset-3">
      <%= review.content %>
       - Rating: <%= review.rating %>
    </li>
  <% end %>
  </ul>
</div>

<div class="container">
  <p><%= link_to "Create a new Review", new_restaurant_review_path(@restaurant) %></p>
</div>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Add a Review</h1>

    <div class="col-xs-12 col-md-offset-3 col-md-6">
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>